spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: zhengshukai
    password: ZHENGshukai
    url: jdbc:mysql://rm-wz9qo2um0eygb0a6qso.mysql.rds.aliyuncs.com:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    publisher-confirms: true
    publisher-returns: true
  redis:
    host: 120.25.217.98
    database: 0
    port: 6379
    password: shukai
  cache:
    cache-names: menus_cache
server:
  port: 8081
  compression:
    enabled: true
